version: '3.2'
services:
  php-fpm:
    # build: ./php/
    image: swarm_php-fpm
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "9001:9000"
    links:
      - mysql-db:mysql-db
      - redis-db:redis-db
    volumes:
      - /web/wwwroot:/data/www:rw
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro # 当前php配置文件；可以拷贝修改php-dev.ini为想要的配置
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./logs/php-fpm:/var/log/php-fpm:rw
    restart: always
    command: php-fpm
    networks:
     - webnet

  nginx:
    # build: ./nginx
    image: swarm_nginx
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    depends_on:
      - php-fpm
    links:
      - php-fpm:php-fpm
    volumes:
      - /web/wwwroot:/data/www:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs/:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    restart: always
    command: nginx -g 'daemon off;'
    networks:
     - webnet


  mysql-db:
      # build: ./mysql
      image: swarm_mysql-db
      ports:
        - "3306:3306"
      volumes:
        - ./data/mysql:/var/lib/mysql:rw
        - ./logs/mysql:/var/lib/mysql-logs:rw
        - ./mysql/conf.d:/etc/mysql/conf.d:ro
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: test
        MYSQL_USER: test
        MYSQL_PASSWORD: test123
      restart: always
      command: "--character-set-server=utf8"
      networks:
       - webnet

  redis-db:
      # build: ./redis
      image: swarm_redis-db
      ports:
        - "6379:6379"
      volumes:
        - ./data/redis:/data
      restart: always
      networks:
       - webnet
          

networks:
  webnet:
